import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'

import './globals.css'

const noto = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Index',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${noto.className} antialiased bg-fixed dark:bg-gradient-to-b dark:from-[#0e1734] dark:to-[#172d69] dark:text-white`}
      >
        {children}
      </body>
    </html>
  )
}
